### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by asadmehdi785** [JaerenTredway/tea_cozy#4]
Overall, good work on this project! Your HTML and CSS was readable and clean, and I liked how you included the `alt` attribute for the images on your webpage. I also really liked how you used HTML5 elements appropriately throughout your HTML, that was very nice to see!

With regards to following the specification, you did a good job, but there was one issue that I noticed. I viewed the webpage in a relatively larger monitor, and it looked like parts of the page didn't stretch to accommodate the width of the monitor. I've provided a screenshot to explain what I'm talking about:

![image](https://user-images.githubusercontent.com/16052289/42842214-8e1d8ae4-89da-11e8-82e9-7bdb9b7cb685.png)

As you can see there, most of the aspects of the webpage are not stretched. However, if I resize the window, then the webpage looks like it should based on the specification. Good effort with that!

Great work overall! I hope you enjoy the rest of the course!

Grade: **Meets expectations**

**Comment by JaerenTredway** [comment]
Thank you for the feedback!
